### ISSUE TITLE
Why is this pipe not being identified as actionable work

### ISSUE THREAD

**Issue by JoeHoffman** [besasm/Rehab---nBCR-Tools#23]
[gethub1.docx](https://github.com/besasm/Rehab---nBCR-Tools/files/98368/gethub1.docx)

**Comment by dboatman** [comment]
Notes:
- Given that the "failure action" (reactive JB) is "Do Nothing", it was filtered out in the first round.
- It's in an environmental zone
- 10" diam, 258' length, ~13' depth
- Hansen grade 4, 3763 def pts total, only one seg above 1000 @ 1101
- 2 prev failures
- The liner cost appears WAY too high. Did we ever get that fixed?
- Replace costs for the bad seg is $7741, whole pipe is $99217
- Failure year is 2042 (26 yrs from now)

My guess is that it is because the segment is 26 yrs from failure, with only one bad seg. The liner option looks like it is coming in way too high though. Any thoughts as to why? Was that due to "replacing all laterals?". Also, have we pushed SPs back to 40 yrs already? (and subsequently all other repairs +10 yrs)

**Comment by MisterGardner** [comment]
This particular pipe receives a 'Do nothing' solution because it requires a gate, and is next to other pipes that require gates.  This is an area where surcharging, grade 4 pipes between replace pipes, and high risk all converge.  

The newer calculations (REHAB_Branches) for liner show the cost of the liner is $46,085.  (Column APWCIPP01)

**Comment by MisterGardner** [comment]
The long term solution for this pipe, under the new processes, shows a spot.  I think that's what we want here.  nBCR_Data shows its a 'Do Nothing' base on extended failure year, which is also what we want (more than 20 years to failure).
